language: node_js
node_js: stable
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
  - cd build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local-dir: build
  fqdn: catalog.linterhub.com
  on:
    branch: master
    target_branch: gh-pages